"
I am a timestamped text answer to a Phex experimental task.
"
Class {
	#name : 'PhexTaskAnswer',
	#superclass : 'Object',
	#instVars : [
		'contents'
	],
	#category : 'PharoExperienceBox-model',
	#package : 'PharoExperienceBox',
	#tag : 'model'
}

{ #category : 'accessing' }
PhexTaskAnswer >> contents [

	^ contents
]

{ #category : 'accessing' }
PhexTaskAnswer >> contents: anObject [

	contents := anObject
]
